Repository labgrid-project/labgrid, pull requests merged in 2018-10, with the labels that each got.

#313 driver/usbtmc: add basic support for Tektronix TDS2000
  labgrid/driver/usbtmc/tektronix_tds2000.py
  labgrid/driver/usbtmcdriver.py
  labgrid/remote/client.py
Labels: enhancement

#322 serialdriver: fix warning string
  labgrid/driver/serialdriver.py
Labels: fix

#308 SSH Tunneling and ManagedFile
  .travis.yml
  CHANGES.rst
  doc/development.rst
  doc/getting_started.rst
  labgrid/driver/fastbootdriver.py
  labgrid/driver/networkusbstoragedriver.py
  labgrid/driver/openocddriver.py
  labgrid/driver/quartushpsdriver.py
  labgrid/driver/serialdriver.py
  labgrid/driver/usbloader.py
  labgrid/pytestplugin/fixtures.py
  labgrid/remote/client.py
  labgrid/remote/exporter.py
  labgrid/util/__init__.py
  labgrid/util/helper.py
  labgrid/util/managedfile.py
  labgrid/util/proxy.py
  labgrid/util/ssh.py
  man/labgrid-exporter.1
  man/labgrid-exporter.rst
  tests/conftest.py
  tests/test_util.py
Labels: enhancement

#329 driver/serialdriver: remove wrong keyword argument
  labgrid/driver/serialdriver.py
Labels: fix

#330 doc: small "getting started" improvements
  doc/getting_started.rst
Labels: documentation

#333 util/proxy: fix docstring for proxy kwarg
  labgrid/util/proxy.py
Labels: fix
