Repository labgrid-project/labgrid, pull requests merged in 2018-03, with the labels that each got.

#209 Search environment for crossbar
  labgrid/remote/client.py
  labgrid/remote/exporter.py
  labgrid/resource/remote.py
  man/Makefile
  man/labgrid-client.1
  man/labgrid-client.rst
  man/labgrid-exporter.1
  man/labgrid-exporter.rst
Labels: enhancement

#197 ubootdriver: make bootstring configurable and update docstring
  doc/configuration.rst
  labgrid/driver/ubootdriver.py
Labels: fix

#217 Increase coverage
  labgrid/protocol/__init__.py
  tests/test_fixtures.py
  tests/test_powerdriver.py
  tests/test_protocol.py
  tests/test_util.py
Labels: enhancement

#191 driver/smallubootdriver: add driver for small UBoots
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/smallubootdriver.py
Labels: enhancement

#208 Add Support for the Pengutronix USB-SD-Mux Hardware
  doc/configuration.rst
  examples/usbsdmux/local.yaml
  examples/usbsdmux/test_sdmux.py
  labgrid/driver/__init__.py
  labgrid/driver/networkusbstoragedriver.py
  labgrid/driver/usbsdmuxdriver.py
  labgrid/driver/usbstorage.py
  labgrid/remote/exporter.py
  labgrid/resource/__init__.py
  labgrid/resource/remote.py
  labgrid/resource/udev.py
Labels: enhancement

#201 implement driver priorities and the ResetProtocol
  doc/development.rst
  doc/overview.rst
  labgrid/driver/__init__.py
  labgrid/driver/common.py
  labgrid/driver/powerdriver.py
  labgrid/driver/resetdriver.py
  labgrid/protocol/__init__.py
  labgrid/protocol/resetprotocol.py
  labgrid/target.py
  tests/test_target.py
Labels: enhancement

#192 driver/powerdriver: Add SerialPortPowerdriver
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/powerdriver.py
  labgrid/driver/serialdigitaloutput.py
Labels: enhancement

#221 Add support for switchable USB hubs via uhubctl
  doc/configuration.rst
  examples/usbpower/cycle.py
  labgrid/driver/__init__.py
  labgrid/driver/powerdriver.py
  labgrid/resource/__init__.py
  labgrid/resource/udev.py
Labels: enhancement

#193 driver/shelldriver: Add 'enable console' feature
  doc/configuration.rst
  labgrid/driver/shelldriver.py
Labels: enhancement

#212 Make the ExecutionError readable for the run_check case
  labgrid/driver/bareboxdriver.py
  labgrid/driver/commandmixin.py
  labgrid/driver/exception.py
  labgrid/driver/shelldriver.py
  labgrid/driver/sshdriver.py
  labgrid/driver/ubootdriver.py
  tests/conftest.py
  tests/test_bareboxdriver.py
  tests/test_shelldriver.py
  tests/test_sshdriver.py
Labels: enhancement, work in progress

#210 Document how to use multiple drivers with names in the yaml configuration files.
  doc/conf.py
  doc/configuration.rst
  doc/usage.rst
  man/labgrid-device-config.1
  man/labgrid-device-config.rst
Labels: documentation
