Repository labgrid-project/labgrid, pull requests merged in 2018-02, with the labels that each got.

#185 remote/client: Added missing speed configuration for microcom console
  labgrid/remote/client.py
Labels: Ready for Merge, enhancement

#189 Add requirements updates from pyup
  README.rst
  crossbar-requirements.txt
  dev-requirements.txt
  doc-requirements.txt
  doc/getting_started.rst
  labgrid/resource/udev.py
  modbus-requirements.txt
  onewire-requirements.txt
  requirements.txt
  setup.py
  snmp-requirements.txt
Labels: enhancement

#195 Remove leftover installation section from overview
  doc/overview.rst
Labels: documentation

#126 sigrok support
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/sigrokdriver.py
  labgrid/remote/exporter.py
  labgrid/resource/remote.py
  labgrid/resource/sigrok.py
  labgrid/resource/udev.py
  tests/conftest.py
  tests/test_sigrok.py
Labels: enhancement, work in progress

#196 README: add link to IRC and Matrix channel
  README.rst
Labels: documentation

#199 Fix Remoteplace regression
  labgrid/resource/remote.py
  tests/conftest.py
  tests/test_crossbar.py
Labels: fix

#202 doc/getting_started: add newline to fix code-block parsing
  doc/getting_started.rst
Labels: documentation
