Repository labgrid-project/labgrid, pull requests merged in 2018-07, with the labels that each got.

#270 driver/openocddriver: multiple improvements
  labgrid/driver/openocddriver.py
Labels: enhancement

#269 resource/udev: add warning if port attribute is set on USBSerialPort
  labgrid/resource/udev.py
  tests/test_environment.py
Labels: documentation, enhancement

#264 linting: declare methods without self-use static and annotate legitimate methods
  labgrid/factory.py
  labgrid/remote/exporter.py
  labgrid/resource/ethernetport.py
  labgrid/resource/udev.py
  labgrid/stepreporter.py
  labgrid/util/agent.py
Labels: enhancement

#237 multiple: add _run function, use _run in _run_check for the mixin
  labgrid/driver/bareboxdriver.py
  labgrid/driver/commandmixin.py
  labgrid/driver/shelldriver.py
  labgrid/driver/smallubootdriver.py
  labgrid/driver/sshdriver.py
  labgrid/driver/ubootdriver.py
  tests/test_bareboxdriver.py
  tests/test_shelldriver.py
  tests/test_sshdriver.py
Labels: fix

#273 Improve usability
  labgrid/driver/serialdriver.py
  labgrid/pytestplugin/fixtures.py
  labgrid/resource/remote.py
  labgrid/strategy/graphstrategy.py
Labels: enhancement

#285 remote/exporter: set LOCAL option for ser2net exported serial ports
  labgrid/remote/exporter.py
Labels: fix

#289 factory: recognize invalid config yaml item in _convert_to_named_list()
  labgrid/factory.py
  tests/test_factory.py
Labels: enhancement
