Repository labgrid-project/labgrid, pull requests merged in 2018-06, with the labels that each got.

#252 ubootdriver.py: Add login_timeout when board takes long time to boot
  doc/configuration.rst
  labgrid/driver/ubootdriver.py
Labels: enhancement

#258 minor factory fixes
  labgrid/factory.py
Labels: fix

#238 doc/development: update ideas section with new features
  doc/development.rst
Labels: documentation

#247 Fix Priorities for get_active_driver
  labgrid/target.py
Labels: fix

#254 Add timeout parameter to run on drivers, to support run_check
  labgrid/driver/fake.py
  labgrid/driver/sshdriver.py
  labgrid/driver/ubootdriver.py
Labels: fix

#262 client: add named access to consoles
  labgrid/remote/client.py
Labels: enhancement

#271 driver/networkusbstoragedriver: fix concatinating tuple to list
  labgrid/driver/networkusbstoragedriver.py
Labels: fix
