Repository labgrid-project/labgrid, pull requests merged in 2019-07, with the labels that each got.

#455 remote/client: use idle place helper for delete
  labgrid/remote/client.py
  tests/test_crossbar.py
Labels: fix

#436 driver: fastbootdriver: implement 'getvar' and 'oem getenv' commands
  CHANGES.rst
  labgrid/driver/fastbootdriver.py
Labels: enhancement, needs author info

#461 tests: add test for flags
  tests/test_flags.py
Labels: enhancement

#459 steps: add exception and duration information
  labgrid/pytestplugin/reporter.py
  labgrid/step.py
  tests/test_step.py
  tests/test_stepreporter.py
Labels: enhancement

#442 resource: common.py only use proxy when 'proxy_required' is true
  labgrid/resource/common.py
Labels: fix

#463 fix onewire PIO input
  labgrid/driver/onewiredriver.py
  tests/test_onewire.py
Labels: fix

#470 pytestplugin/hooks: fix capture check
  labgrid/pytestplugin/hooks.py
Labels: fix

#471 pytestplugin/hooks: register lg_feature marker
  labgrid/pytestplugin/hooks.py
Labels: fix

#467 pytestplugin/fixtures: use request.config
  labgrid/pytestplugin/fixtures.py
Labels: fix

#477 graphstrategy: raise if via is not list or None
  labgrid/strategy/graphstrategy.py
  tests/test_graphstrategy.py
Labels: enhancement, needs jluebbe attention

#473 driver/onewiredriver: add steps to get and set
  labgrid/driver/onewiredriver.py
Labels: enhancement, needs jluebbe attention

#476 ubootdriver: use the given timeout for run()
  labgrid/driver/ubootdriver.py
Labels: enhancement, needs jluebbe attention

#468 Implement GPIO support via sysfs with agent interface
  CHANGES.rst
  doc/configuration.rst
  examples/sysfsgpio/export-gpio.yaml
  examples/sysfsgpio/import-gpio.yaml
  examples/sysfsgpio/sysfsgpio.py
  examples/sysfsgpio/sysfsgpio_remote.py
  labgrid/driver/__init__.py
  labgrid/driver/gpiodriver.py
  labgrid/remote/client.py
  labgrid/remote/exporter.py
  labgrid/resource/base.py
  labgrid/resource/remote.py
  labgrid/util/agents/sysfsgpio.py
  tests/test_agent.py
  tests/test_sysfsgpioagent.py
Labels: enhancement, needs jluebbe attention

#480 Minor coordinator fixes and cleanups
  labgrid/remote/coordinator.py
  labgrid/util/__init__.py
  labgrid/util/atomic.py
  tests/test_crossbar.py
Labels: fix
