Repository labgrid-project/labgrid, pull requests merged in 2019-08, with the labels that each got.

#482 doc/development: remove implemented ideas
  doc/development.rst
Labels: documentation

#478 doc: add RELEASE.rst file for maintainers
  doc/RELEASE.rst
  doc/conf.py
Labels: documentation

#408 Add a FileDigitalOutputDriver
  CHANGES.rst
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/filedigitaloutput.py
  tests/test_filedigitaloutput.py
Labels: enhancement, needs author info

#485 Fix client strategy
  labgrid/remote/client.py
Labels: fix
