Repository labgrid-project/labgrid, pull requests merged in 2019-05, with the labels that each got.

#395 Documentation improvements
  doc/configuration.rst
  labgrid/driver/shelldriver.py
Labels: documentation

#419 resource/udev: add backlog for udev
  labgrid/resource/udev.py
Labels: fix

#426 Topic/debian
  debian/labgrid-client
  debian/labgrid-exporter
  debian/labgrid-pytest
  debian/labgrid.install
  debian/labgrid.yaml
  debian/rules
Labels: enhancement, fix

#427 remote/client: support env variables in namespace
  labgrid/remote/client.py
  man/labgrid-client.1
  man/labgrid-client.rst
Labels: enhancement

#431 driver: fastbootdriver: don't disable sparsing by default
  doc/configuration.rst
  labgrid/driver/fastbootdriver.py
Labels: fix

#428 Extended SSH Proxy Support
  CHANGES.rst
  doc/usage.rst
  labgrid/driver/modbusdriver.py
  labgrid/driver/onewiredriver.py
  labgrid/driver/power/apc.py
  labgrid/driver/power/digipower.py
  labgrid/driver/power/gude.py
  labgrid/driver/power/gude24.py
  labgrid/driver/power/gude8316.py
  labgrid/driver/power/netio.py
  labgrid/driver/power/netio_kshell.py
  labgrid/driver/power/simplerest.py
  labgrid/driver/powerdriver.py
  labgrid/remote/client.py
  labgrid/resource/common.py
  labgrid/util/proxy.py
  labgrid/util/ssh.py
  man/labgrid-client.1
  man/labgrid-client.rst
  tests/test_onewire.py
Labels: enhancement

#432 Add agent module, resource and driver for Dedidec Relais 8 device
  examples/deditec-relais8/deditec.py
  examples/deditec-relais8/deditec_remote.py
  examples/deditec-relais8/export-didicontrol.yaml
  examples/deditec-relais8/import-dedicontrol.yaml
  labgrid/driver/deditecrelaisdriver.py
  labgrid/remote/client.py
  labgrid/remote/exporter.py
  labgrid/resource/remote.py
  labgrid/resource/udev.py
  labgrid/util/agent.py
  labgrid/util/agents/deditec_relais8.py
  labgrid/util/agentwrapper.py
  requirements.txt
  tests/test_agent.py
Labels: enhancement
