Repository labgrid-project/labgrid, pull requests merged in 2019-09, with the labels that each got.

#481 Acquire resources on exporter
  CHANGES.rst
  labgrid/remote/client.py
  labgrid/remote/common.py
  labgrid/remote/coordinator.py
  labgrid/remote/exporter.py
  tests/test_crossbar.py
Labels: breaking, enhancement

#469 Subprocess Wrapper
  labgrid/driver/fastbootdriver.py
  labgrid/driver/flashromdriver.py
  labgrid/driver/networkusbstoragedriver.py
  labgrid/driver/openocddriver.py
  labgrid/driver/power/apc.py
  labgrid/driver/powerdriver.py
  labgrid/driver/quartushpsdriver.py
  labgrid/driver/usbloader.py
  labgrid/driver/usbsdmuxdriver.py
  labgrid/pytestplugin/hooks.py
  labgrid/remote/client.py
  labgrid/util/helper.py
  tests/test_powerdriver.py
Labels: enhancement

#301 Docker integration
  dev-requirements.txt
  doc/configuration.rst
  docker-requirements.txt
  examples/docker/README.md
  examples/docker/conftest.py
  examples/docker/env.yaml
  examples/docker/test_shell.py
  labgrid/driver/__init__.py
  labgrid/driver/dockerdriver.py
  labgrid/resource/__init__.py
  labgrid/resource/docker.py
  labgrid/strategy/__init__.py
  labgrid/strategy/dockerstrategy.py
  labgrid/util/__init__.py
  labgrid/util/dict.py
  tests/test_docker.py
  tests/test_util.py
Labels: work in progress

#483 place reservation
  doc/development.rst
  doc/getting_started.rst
  doc/overview.rst
  doc/usage.rst
  labgrid/remote/client.py
  labgrid/remote/common.py
  labgrid/remote/coordinator.py
  labgrid/remote/scheduler.py
  man/labgrid-client.1
  man/labgrid-client.rst
  tests/test_crossbar.py
  tests/test_sched.py
Labels: breaking, enhancement

#494 Doc/updates
  doc/development.rst
  man/labgrid-client.1
  man/labgrid-client.rst
  man/labgrid-device-config.1
  man/labgrid-device-config.rst
Labels: documentation

#496 shelldriver: use remaining timeout after password
  labgrid/driver/shelldriver.py
Labels: enhancement

#495 remote/common: replace → to support C locale
  labgrid/remote/common.py
Labels: fix

#501 util/proxy: remove leftover debug print
  labgrid/util/proxy.py
Labels: fix
