Repository labgrid-project/labgrid, pull requests merged in 2019-06, with the labels that each got.

#445 README: update travis-ci badge
  README.rst
Labels: documentation

#446 resource/udev: add VID and PID for i.MX8MQ
  labgrid/resource/udev.py
Labels: enhancement

#444 driver: openocddriver: use AlteraUSBBlaster's USB path
  doc/configuration.rst
  labgrid/driver/openocddriver.py
Labels: documentation, needs jluebbe attention

#452 close labgrid-client console connection on place release
  labgrid/remote/client.py
  labgrid/remote/common.py
Labels: fix

#437 RKUsbLoader/RKUSBDriver and minor fixes
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/networkusbstoragedriver.py
  labgrid/driver/usbloader.py
  labgrid/remote/client.py
  labgrid/remote/exporter.py
  labgrid/resource/remote.py
  labgrid/resource/udev.py
Labels: enhancement, needs author info

#456 crossbar: remove event store enabled by default
  .crossbar/config.yaml
Labels: enhancement

#348 flashrom: Add support for flashing ROM's by the flashrom utility
  CHANGES.rst
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/flashromdriver.py
  labgrid/resource/__init__.py
  labgrid/resource/flashrom.py
  tests/test_flashrom.py
Labels: enhancement, needs author info
