Repository labgrid-project/labgrid, pull requests merged in 2019-02, with the labels that each got.

#381 remote/client: let fastboot use driver functions
  labgrid/remote/client.py
Labels: fix

#386 docker: README.rst: some markup fixes
  docker/README.rst
Labels: documentation

#242 driver/commandmixin: Add poll_until_success helper function
  labgrid/driver/commandmixin.py
  labgrid/protocol/commandprotocol.py
Labels: enhancement
