Repository labgrid-project/labgrid, pull requests merged in 2020-01, with the labels that each got.

#547 coordinator and client robustness fixes
  crossbar-requirements.txt
  dev-requirements.txt
  labgrid/remote/client.py
  labgrid/remote/coordinator.py
  labgrid/remote/exporter.py
  requirements.txt
  tests/conftest.py
  tests/test_crossbar.py
Labels: fix

#551 doc: Link 'Overview' Chapters From 'Getting Started' Chapter
  doc/getting_started.rst
  doc/overview.rst
Labels: documentation

#560 exporter broken tracking
  labgrid/remote/exporter.py
  tests/conftest.py
  tests/test_crossbar.py
Labels: fix

#511 Convert drivers from imports to strings
  labgrid/driver/deditecrelaisdriver.py
  labgrid/driver/dockerdriver.py
  labgrid/driver/fastbootdriver.py
  labgrid/driver/flashromdriver.py
  labgrid/driver/gpiodriver.py
  labgrid/driver/modbusdriver.py
  labgrid/driver/networkusbstoragedriver.py
  labgrid/driver/onewiredriver.py
  labgrid/driver/openocddriver.py
  labgrid/driver/powerdriver.py
  labgrid/driver/quartushpsdriver.py
  labgrid/driver/serialdriver.py
  labgrid/driver/sshdriver.py
  labgrid/driver/usbloader.py
  labgrid/driver/usbsdmuxdriver.py
  labgrid/driver/usbstorage.py
  labgrid/driver/usbtmcdriver.py
  labgrid/driver/usbvideodriver.py
  labgrid/driver/xenadriver.py
  labgrid/factory.py
  labgrid/target.py
Labels: enhancement

#562 improve async scheduling
  labgrid/remote/coordinator.py
  labgrid/remote/exporter.py
Labels: fix
