Repository labgrid-project/labgrid, pull requests merged in 2020-10, with the labels that each got.

#648 util/proxy: prefer isolated over LG_PROXY
  doc/overview.rst
  labgrid/util/proxy.py
Labels: enhancement, fix

#586 driver/power/gude24.py: Raise execution error if device is blocked
  labgrid/driver/power/gude24.py
Labels: bug, enhancement

#625 Power Driver for Gude8031
  labgrid/driver/power/gude8031.py
Labels: enhancement

#649 doc/configuration: document USB hub interfaces
  doc/configuration.rst
Labels: documentation

#653 util/helper: use low level read for PTY
  labgrid/util/helper.py
Labels: fix

#651 lxaiobus: support for LXA IO Bus nodes
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/lxaiobusdriver.py
  labgrid/remote/client.py
  labgrid/remote/exporter.py
  labgrid/resource/__init__.py
  labgrid/resource/lxaiobus.py
  labgrid/resource/remote.py
  tests/test_lxaiobus.py
Labels: enhancement
