Repository labgrid-project/labgrid, pull requests merged in 2021-09, with the labels that each got.

#827 Improve docs, update Driver doc strings
  doc/configuration.rst
  doc/usage.rst
  labgrid/driver/bareboxdriver.py
  labgrid/driver/shelldriver.py
  labgrid/driver/ubootdriver.py
Labels: documentation

#822 resource/udev: handle multiple resources on single device correctly
  labgrid/resource/udev.py
Labels: fix

#830 remote/config: support jinja2 includes
  labgrid/remote/config.py
Labels: enhancement

#831 doc: simplify getting_started/usage, make installation steps more consistent
  doc/getting_started.rst
  doc/usage.rst
Labels: documentation

#807 proxy: add ProxyError, check host and port
  labgrid/util/proxy.py
Labels: enhancement

#836 test/flashscript: skip tests if binaries missing
  tests/test_flashscript.py
Labels: fix

#837 util/ssh: fix control master check
  labgrid/util/ssh.py
Labels: fix

#668 driver: add eaton epdu network power driver
  CHANGES.rst
  examples/power/env.yaml
  examples/power/power_example.py
  labgrid/driver/power/eaton.py
  tests/test_powerdriver.py
Labels: enhancement
