Repository labgrid-project/labgrid, pull requests merged in 2021-07, with the labels that each got.

#764 Add IP Video support
  doc/configuration.rst
  labgrid/driver/httpvideodriver.py
  labgrid/driver/usbvideodriver.py
  labgrid/protocol/__init__.py
  labgrid/protocol/videoprotocol.py
  labgrid/remote/client.py
  labgrid/remote/exporter.py
  labgrid/resource/__init__.py
  labgrid/resource/httpvideostream.py
  tests/test_httpvideo.py
Labels: work in progress

#796 driver/fastbootdriver: remove vendor_id matching
  labgrid/driver/fastbootdriver.py
Labels: fix

#775 shelldriver: Handle intermingled output on login
  doc/configuration.rst
  labgrid/driver/consoleexpectmixin.py
  labgrid/driver/shelldriver.py
Labels: enhancement

#795 remote/client: fix automatic driver selection
  labgrid/remote/client.py
Labels: bug

#798 remote/exporter: info print ser2net command
  labgrid/remote/exporter.py
Labels: enhancement

#759 driver/usbvideodriver: add basic MacroSilicon USB Video support
  labgrid/driver/usbvideodriver.py
  labgrid/remote/client.py
Labels: enhancement
