Repository labgrid-project/labgrid, pull requests merged in 2021-04, with the labels that each got.

#766 add support for Linux Automation USB-Mux
  doc/configuration.rst
  labgrid/driver/lxausbmuxdriver.py
  labgrid/remote/client.py
  labgrid/remote/exporter.py
  labgrid/resource/remote.py
  labgrid/resource/suggest.py
  labgrid/resource/udev.py
Labels: enhancement

#741 add NetworkManager remote control via agent
  doc/conf.py
  doc/configuration.rst
  examples/networkmanager/nm.env
  examples/networkmanager/nm.py
  labgrid/driver/__init__.py
  labgrid/driver/networkinterfacedriver.py
  labgrid/remote/exporter.py
  labgrid/resource/__init__.py
  labgrid/resource/base.py
  labgrid/resource/remote.py
  labgrid/resource/suggest.py
  labgrid/resource/udev.py
  labgrid/util/agents/network_interface.py
Labels: enhancement

#762 TFTP/NFS/HTTP providers
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/provider.py
  labgrid/provider/__init__.py
  labgrid/provider/fileprovider.py
  labgrid/provider/mediafileprovider.py
  labgrid/remote/exporter.py
  labgrid/resource/__init__.py
  labgrid/resource/provider.py
  labgrid/resource/remote.py
  labgrid/util/managedfile.py
  setup.py
  tests/test_mediafileprovider.py
Labels: enhancement

#772 exporter: Check /usr/sbin for ser2net
  CHANGES.rst
  labgrid/remote/exporter.py
Labels: ready for merge

#557 contrib/systemd: add systemd services
  contrib/systemd/labgrid-coordinator.service
  contrib/systemd/labgrid-exporter.service
  contrib/systemd/sysusers.d/labgrid.conf
  contrib/systemd/tmpfiles.d/labgrid.conf
  doc/getting_started.rst
Labels: enhancement

#698 mqtt: support for tasmota power ports
  dev-requirements.txt
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/mqtt.py
  labgrid/remote/client.py
  labgrid/resource/__init__.py
  labgrid/resource/mqtt.py
  labgrid/resource/remote.py
  mqtt-requirements.txt
  tests/test_tasmota.py
Labels: enhancement

#663 docs: improve library usage docs
  doc/configuration.rst
  doc/usage.rst
  labgrid/driver/bareboxdriver.py
  labgrid/driver/shelldriver.py
Labels: documentation
