Repository labgrid-project/labgrid, pull requests merged in 2021-01, with the labels that each got.

#703 CHANGES: update for release v0.3.0
  CHANGES.rst
Labels: documentation

#705 doc: development: fix custom strategy skeleton
  doc/development.rst
Labels: documentation

#700 resource: DeditecRelais8: add ID_MODEL
  labgrid/resource/udev.py
Labels: fix

#702 labgrid-bound-connect: Delete IP cache
  helpers/labgrid-bound-connect
Labels: ready for merge

#690 client: Add LG_CLAIM_HOSTNAME/LG_CLAIM_USER
  CHANGES.rst
  labgrid/remote/client.py
  man/labgrid-client.rst
Labels: enhancement, ready for merge

#523 doc: fix small inconsistency in the getting started
  doc/getting_started.rst
Labels: ready for merge, work in progress

#577 driver: add invert to SerialDigitalOutputDriver
  doc/configuration.rst
  labgrid/driver/serialdigitaloutput.py
Labels: enhancement

#636 driver/pyvisadriver: add driver to support PyVISA
  CHANGES.rst
  dev-requirements.txt
  doc/configuration.rst
  examples/pyvisa/env.yaml
  examples/pyvisa/pyvisa_example.py
  labgrid/driver/__init__.py
  labgrid/driver/pyvisadriver.py
  labgrid/resource/__init__.py
  labgrid/resource/pyvisa.py
  pyvisa-requirements.txt
  tests/test_pyvisa.py
Labels: enhancement, needs author info, ready for merge
