Repository labgrid-project/labgrid, pull requests merged in 2021-02, with the labels that each got.

#712 target: duplicate bindings under differing names
  labgrid/target.py
  tests/test_target.py
Labels: enhancement

#717 driver/power: add support for Siglent SPD3000X series power supplies
  CHANGES.rst
  dev-requirements.txt
  labgrid/driver/power/siglent.py
  tests/test_powerdriver.py
  vxi11-requirements.txt
Labels: enhancement

#722 exporter: Correctly handle serial baud rates other than 115200
  labgrid/remote/exporter.py
Labels: Pick to stable, fix

#725 exporter: fix SerialPortExport start params
  labgrid/remote/exporter.py
Labels: fix

#718 add support for USB HID relays
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/usbhidrelay.py
  labgrid/protocol/digitaloutputprotocol.py
  labgrid/remote/exporter.py
  labgrid/resource/remote.py
  labgrid/resource/udev.py
  labgrid/util/agents/usb_hid_relay.py
  tests/test_agent.py
Labels: enhancement
