Repository labgrid-project/labgrid, pull requests merged in 2022-11, with the labels that each got.

#1027 add timeout to docker-compose client, gather logs on error
  .github/workflows/unit-tests.yml
  dockerfiles/staging/docker-compose.yml
Labels: tests, docker

#1029 requirements: bump attrs 21.2.0 -> 21.3.0
  requirements.txt
Labels: dependencies

#1032 requirements: bump attrs 21.3.0 -> 21.4.0
  requirements.txt
Labels: dependencies

#1001 Switch to pyproject.toml
  .github/workflows/docker.yml
  .github/workflows/unit-tests.yml
  MANIFEST.in
  README.rst
  ci-requirements.txt
  crossbar-requirements.txt
  deb-requirements.txt
  debian/copyright
  debian/rules
  dev-requirements.txt
  doc-requirements.txt
  doc/RELEASE.rst
  doc/development.rst
  doc/getting_started.rst
  docker-requirements.txt
  dockerfiles/Dockerfile
  dockerfiles/README.rst
  dockerfiles/build.sh
  fastentrypoints.py
  graph-requirements.txt
  kasa-requirements.txt
  modbus-requirements.txt
  modbusrtu-requirements.txt
  mqtt-requirements.txt
  onewire-requirements.txt
  pyproject.toml
  pyvisa-requirements.txt
  requirements.txt
  setup.cfg
  setup.py
  snmp-requirements.txt
  tox.ini
  vxi11-requirements.txt
  xena-requirements.txt
Labels: dependencies

#1036 add readthedocs configuration
  .readthedocs.yaml
Labels: documentation, fix

#967 add port-forwarding helpers on the NetworkInterfaceDriver
  CHANGES.rst
  labgrid/driver/common.py
  labgrid/driver/networkinterfacedriver.py
  labgrid/driver/sshdriver.py
  labgrid/target.py
  labgrid/util/agentwrapper.py
  labgrid/util/ssh.py
  tests/test_util.py
Labels: enhancement
