Repository labgrid-project/labgrid, pull requests merged in 2022-08, with the labels that each got.

#966 tests: record coordinator's coverage
  .crossbar/config.yaml
  tests/conftest.py
Labels: tests

#970 driver/qemudriver: fix disk attribute for vexpress-a9 machine
  labgrid/driver/qemudriver.py
Labels: fix

#971 resouce/suggest: add basic support for USBPowerPorts
  labgrid/resource/suggest.py
Labels: enhancement

#960 driver/power/siglent: use backend function signatures expected by NetworkPowerDriver
  labgrid/driver/power/siglent.py
Labels: fix, Pick to stable

#959 driver: fastbootdriver: support fastboot over network
  doc/configuration.rst
  doc/overview.rst
  labgrid/driver/fastbootdriver.py
  labgrid/remote/exporter.py
  labgrid/resource/fastboot.py
  labgrid/resource/remote.py
  labgrid/resource/suggest.py
  labgrid/resource/udev.py
  tests/test_environment.py
Labels: enhancement
