Repository labgrid-project/labgrid, pull requests merged in 2022-01, with the labels that each got.

#877 Documentation fixes and improvements
  CHANGES.rst
  README.rst
  doc/configuration.rst
  doc/development.rst
  doc/getting_started.rst
  doc/overview.rst
  doc/usage.rst
  examples/usbpower/examplestrategy.py
  labgrid/driver/bareboxdriver.py
  labgrid/driver/ubootdriver.py
  labgrid/protocol/commandprotocol.py
  labgrid/protocol/infoprotocol.py
  labgrid/resource/serialport.py
  labgrid/resource/sigrok.py
  labgrid/resource/udev.py
  labgrid/resource/xenamanager.py
  labgrid/strategy/bareboxstrategy.py
  labgrid/strategy/graphstrategy.py
  labgrid/strategy/ubootstrategy.py
  labgrid/target.py
  man/labgrid-device-config.5
  man/labgrid-device-config.rst
Labels: documentation

#876 driver: import missing drivers in __init__.py
  labgrid/driver/__init__.py
Labels: enhancement

#878 util/managedfile: do not check file creation time in NFS check
  doc/development.rst
  labgrid/util/managedfile.py
Labels: fix

#879 tests/test_docker: handle docker.errors.DockerException
  tests/test_docker.py
Labels: tests

#880 use deferred imports for requests and pyudev
  labgrid/driver/lxaiobusdriver.py
  labgrid/resource/lxaiobus.py
  labgrid/resource/udev.py
Labels: enhancement

#882 doc: test code/config snippets in docs
  .github/workflows/unit-tests.yml
  doc/conf.py
  doc/configuration.rst
  doc/development.rst
  doc/getting_started.rst
  doc/overview.rst
  doc/usage.rst
Labels: documentation

#797 driver/power: Add backend driver for EG PMS2 LAN/WLAN
  CHANGES.rst
  doc/configuration.rst
  labgrid/driver/power/eg_pms2_network.py
  tests/test_powerdriver.py
Labels: enhancement

#884 README: update currently supported features
  README.rst
Labels: documentation

#885 doc: add logo/favicon
  doc/conf.py
  doc/images/favicon.png
  doc/images/labgrid_logo_outline.svg
Labels: documentation

#886 doc: index: apply README changes
  doc/index.rst
Labels: documentation

#883 Import fixes
  labgrid/driver/httpvideodriver.py
  labgrid/driver/shelldriver.py
  labgrid/remote/client.py
Labels: fix
