Repository labgrid-project/labgrid, pull requests merged in 2022-09, with the labels that each got.

#974 driver/openocddriver: fix command quoting and add tests
  .github/workflows/unit-tests.yml
  labgrid/driver/openocddriver.py
  tests/test_openocd.py
Labels: fix

#977 driver/ubootdriver: Fix reset method
  labgrid/driver/ubootdriver.py
Labels: fix, Pick to stable

#973 util/qmp: log representation of line instead of line
  labgrid/util/qmp.py
Labels: fix

#1000 tests: make tests compatible with recent versions of autobahn/docker
  doc/configuration.rst
  tests/conftest.py
Labels: tests

#999 requirements/setup.cfg: drop yapf
  dev-requirements.txt
  setup.cfg
Labels: dependencies

#995 Added Olimex USBDebugger IDs
  labgrid/resource/udev.py
Labels: enhancement

#998 doc/man: fixes and improvements for recent sphinx doc/man generation
  .github/workflows/unit-tests.yml
  doc/Makefile
  doc/conf.py
  setup.cfg
Labels: documentation

#994 Fix relevant pylint warnings, run basic pylint checks in CI
  .github/workflows/unit-tests.yml
  .pylintrc
  labgrid/autoinstall/main.py
  labgrid/binding.py
  labgrid/driver/bareboxdriver.py
  labgrid/driver/deditecrelaisdriver.py
  labgrid/driver/dfudriver.py
  labgrid/driver/externalconsoledriver.py
  labgrid/driver/fake.py
  labgrid/driver/fastbootdriver.py
  labgrid/driver/flashromdriver.py
  labgrid/driver/flashscriptdriver.py
  labgrid/driver/httpvideodriver.py
  labgrid/driver/lxausbmuxdriver.py
  labgrid/driver/networkinterfacedriver.py
  labgrid/driver/openocddriver.py
  labgrid/driver/provider.py
  labgrid/driver/quartushpsdriver.py
  labgrid/driver/serialdriver.py
  labgrid/driver/shelldriver.py
  labgrid/driver/sigrokdriver.py
  labgrid/driver/smallubootdriver.py
  labgrid/driver/sshdriver.py
  labgrid/driver/ubootdriver.py
  labgrid/driver/usbhidrelay.py
  labgrid/driver/usbloader.py
  labgrid/driver/usbsdmuxdriver.py
  labgrid/driver/usbsdwiredriver.py
  labgrid/driver/usbstoragedriver.py
  labgrid/driver/usbtmcdriver.py
  labgrid/driver/usbvideodriver.py
  labgrid/environment.py
  labgrid/pytestplugin/reporter.py
  labgrid/remote/client.py
  labgrid/remote/common.py
  labgrid/remote/coordinator.py
  labgrid/remote/exporter.py
  labgrid/remote/scheduler.py
  labgrid/resource/common.py
  labgrid/resource/remote.py
  labgrid/resource/udev.py
  labgrid/step.py
  labgrid/strategy/__init__.py
  labgrid/strategy/bareboxstrategy.py
  labgrid/strategy/shellstrategy.py
  labgrid/strategy/ubootstrategy.py
  labgrid/util/agent.py
  labgrid/util/agents/network_interface.py
  labgrid/util/agents/usb_hid_relay.py
  labgrid/util/helper.py
  labgrid/util/ssh.py
  pyproject.toml
  tox.ini
Labels: tests

#1011 Allow Command Wraping in NetworkResources, Use it in OpenOCDDriver
  labgrid/driver/openocddriver.py
  labgrid/resource/common.py
Labels: fix

#981 util: expect: implement sendcontrol()
  labgrid/util/expect.py
Labels: enhancement

#1010 doc/configuration: add note about bracketed-paste mode
  doc/configuration.rst
Labels: documentation
