Repository labgrid-project/labgrid, pull requests merged in 2022-06, with the labels that each got.

#934 remote/client: optionally show used exporters with 'who'
  labgrid/remote/client.py
Labels: enhancement

#932 man: fix crossbar option, add missing subcommands
  man/labgrid-client.1
  man/labgrid-client.rst
  man/labgrid-exporter.1
  man/labgrid-exporter.rst
Labels: documentation, fix

#933 Introduce DFUDevice, DFUDriver
  CHANGES.rst
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/dfudriver.py
  labgrid/remote/client.py
  labgrid/remote/exporter.py
  labgrid/resource/remote.py
  labgrid/resource/suggest.py
  labgrid/resource/udev.py
  man/labgrid-client.1
  man/labgrid-client.rst
Labels: enhancement

#940 driver/qemudriver: let _read() handle max_size kwarg
  labgrid/driver/qemudriver.py
  tests/test_qemudriver.py
Labels: fix

#941 remote/client: update resources before checking NetworkSerialPort availability
  labgrid/remote/client.py
Labels: fix
