Repository labgrid-project/labgrid, pull requests merged in 2023-07, with the labels that each got.

#1226 github/workflows: add scheduled test jobs for stable branch
  .github/workflows/scheduled-unit-tests.yml
Labels: CI

#1235 doc/configuration: syntax fixes
  doc/configuration.rst
Labels: documentation

#1222 remote/coordinator: fix resetting places to an empty set
  labgrid/remote/coordinator.py
Labels: fix

#1240 pyproject: use PyYAML 6.0.1
  pyproject.toml
Labels: fix for stable

#1242 driver/bareboxdriver: run commands with saved log level
  CHANGES.rst
  labgrid/driver/bareboxdriver.py
Labels: enhancement

#1237 pyproject: use PyYAML 6.0.1
  pyproject.toml
Labels: fix, dependencies

#1141 driver/sigrok: Add sigrok driver for DMMs
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/sigrokdriver.py
Labels: enhancement

#1223 driver/shelldriver: fix status attribute setting
  labgrid/driver/shelldriver.py
Labels: fix

#1250 doc/configuration: small fixes
  doc/configuration.rst
Labels: documentation
