Repository labgrid-project/labgrid, pull requests merged in 2023-12, with the labels that each got.

#1306 Test with Python 3.12, but don't advertise it, yet
  .github/workflows/push-pr-unit-tests.yml
  .github/workflows/scheduled-unit-tests.yml
  tests/test_crossbar.py
Labels: tests

#1293 driver/resources: use consistent logger names
  labgrid/driver/bareboxdriver.py
  labgrid/driver/common.py
  labgrid/driver/dediprogflashdriver.py
  labgrid/driver/dockerdriver.py
  labgrid/driver/externalconsoledriver.py
  labgrid/driver/fake.py
  labgrid/driver/flashromdriver.py
  labgrid/driver/flashscriptdriver.py
  labgrid/driver/openocddriver.py
  labgrid/driver/qemudriver.py
  labgrid/driver/quartushpsdriver.py
  labgrid/driver/serialdriver.py
  labgrid/driver/shelldriver.py
  labgrid/driver/sigrokdriver.py
  labgrid/driver/sshdriver.py
  labgrid/driver/ubootdriver.py
  labgrid/driver/usbaudiodriver.py
  labgrid/driver/usbstoragedriver.py
  labgrid/driver/usbvideodriver.py
  labgrid/driver/xenadriver.py
  labgrid/resource/common.py
  labgrid/resource/docker.py
  labgrid/resource/ethernetport.py
  labgrid/resource/lxaiobus.py
  labgrid/resource/mqtt.py
  labgrid/resource/remote.py
  labgrid/resource/udev.py
  labgrid/util/qmp.py
Labels: enhancement

#1309 driver: qemudriver: fold equivalent disk arguments
  labgrid/driver/qemudriver.py
Labels: enhancement

#1308 shelldriver: allow login with empty password
  CHANGES.rst
  doc/configuration.rst
  labgrid/driver/shelldriver.py
Labels: enhancement

#1275 power: add eth008 power backend
  doc/configuration.rst
  labgrid/driver/power/eth008.py
  tests/test_powerdriver.py
Labels: enhancement

#1254 Minor Sigrok Improvements
  labgrid/driver/sigrokdriver.py
Labels: needs device testing

#1305 driver/sshdriver: Add credential overriding NetworkService's
  doc/configuration.rst
  labgrid/driver/sshdriver.py
Labels: enhancement

#1310 examples: add sigrok example
  examples/sigrok/env.yaml
  examples/sigrok/main.py
Labels: enhancement
