Repository labgrid-project/labgrid, pull requests merged in 2023-08, with the labels that each got.

#1252 resource: import missing resources
  labgrid/resource/__init__.py
Labels: enhancement

#1233 util/managedfile: resolve symlinks before comparing NFS paths
  CHANGES.rst
  labgrid/util/managedfile.py
  tests/test_flashscript.py
Labels: fix

#1227 dockerfiles: bump base image bullseye -> bookworm
  dockerfiles/Dockerfile
  dockerfiles/staging/dut/Dockerfile
Labels: docker

#1256 dockerfiles/dut: fix --chown option
  dockerfiles/staging/dut/Dockerfile
Labels: Pick to stable, docker

#1257 pyproject.toml: require Sphinx>=2.0.0 for doc feature
  pyproject.toml
Labels: documentation, fix
