Repository labgrid-project/labgrid, pull requests merged in 2023-05, with the labels that each got.

#1159 doc/conf: add sphinx_rtd_theme to extensions to fix jQuery loading
  doc/conf.py
Labels: documentation, fix

#1160 README and documentation improvements
  README.rst
  doc/getting_started.rst
Labels: documentation

#1161 README: fix RST syntax and introduce check
  .github/workflows/reusable-unit-tests.yml
  README.rst
Labels: documentation, fix, CI

#1156 driver/power: add raritan pdu network power driver
  doc/configuration.rst
  labgrid/driver/power/eaton.py
  labgrid/driver/power/raritan.py
  labgrid/util/snmp.py
Labels: enhancement

#1165 github/workflows/docker: push tags
  .github/workflows/docker.yml
Labels: enhancement

#1164 pyproject: add more classifiers
  pyproject.toml
Labels: enhancement

#1125 Add print version subcommand.
  contrib/completion/labgrid-client.bash
  labgrid/remote/client.py
  labgrid/remote/exporter.py
  labgrid/util/__init__.py
  labgrid/util/version.py
  man/labgrid-client.1
  man/labgrid-client.rst
Labels: enhancement

#1172 contrib/systemd/labgrid-exporter: add plugdev to SupplementaryGroups
  contrib/systemd/labgrid-exporter.service
  doc/getting_started.rst
Labels: fix

#1181 driver/usbloader: enable print_on_silent_log for subprocess calls
  labgrid/driver/usbloader.py
Labels: enhancement

#1170 util/atomic: fix UnboundLocalError in atomic_replace()
  labgrid/util/atomic.py
Labels: fix

#1091 dockerfiles: support for docker buildx
  dockerfiles/README.rst
  dockerfiles/build.sh
Labels: enhancement, docker

#1166 config: return passed in tool by default
  labgrid/config.py
  labgrid/driver/dfudriver.py
  labgrid/driver/fastbootdriver.py
  labgrid/driver/lxausbmuxdriver.py
  labgrid/driver/openocddriver.py
  labgrid/driver/powerdriver.py
  labgrid/driver/quartushpsdriver.py
  labgrid/driver/usbloader.py
  labgrid/driver/usbsdmuxdriver.py
  labgrid/driver/usbsdwiredriver.py
  tests/test_config.py
Labels: enhancement

#1182 drivers, resource: implement get_bound_resources()
  labgrid/binding.py
  labgrid/driver/common.py
  labgrid/resource/common.py
  labgrid/target.py
  tests/test_target.py
Labels: enhancement
