Repository labgrid-project/labgrid, pull requests merged in 2023-09, with the labels that each got.

#1264 remote/client: do not print deleted resource's class on monitor
  labgrid/remote/client.py
Labels: fix

#1212 qemudriver: export get_qemu_base_args method
  labgrid/driver/qemudriver.py
Labels: Ready for review

#1262 sshdriver: Add Port Forwarding to Unix Sockets
  labgrid/driver/sshdriver.py
  tests/test_sshdriver.py
Labels: enhancement

#1271 github: workflows: update GitHub actions to latest versions
  .github/workflows/build-and-release.yml
  .github/workflows/docker.yml
  .github/workflows/reusable-unit-tests-docker.yml
  .github/workflows/reusable-unit-tests.yml
Labels: CI

#1268 tests: test different resources having a default
  tests/test_target.py
Labels: enhancement

#1265 ssh: Prevent timeout from deadlock
  labgrid/driver/sshdriver.py
  labgrid/util/ssh.py
  tests/test_sshdriver.py
Labels: fix
