Repository labgrid-project/labgrid, pull requests merged in 2023-04, with the labels that each got.

#1134 github: reusable-unit-tests: do not install codecov/coveralls
  .github/workflows/reusable-unit-tests.yml
Labels: tests, CI

#1135 Allow setting initial Strategy state in client
  contrib/completion/labgrid-client.bash
  labgrid/remote/client.py
  man/labgrid-client.1
  man/labgrid-client.rst
Labels: enhancement

#1115 driver/resource: Support dediprog
  doc/configuration.rst
  labgrid/driver/__init__.py
  labgrid/driver/dediprogflashdriver.py
  labgrid/resource/__init__.py
  labgrid/resource/dediprogflasher.py
  man/labgrid-device-config.5
  man/labgrid-device-config.rst
  tests/test_dediprogflasher.py
Labels: enhancement

#1137 remote/client: return exit code for ssh/scp/rsync/telnet/video/audio/console
  labgrid/driver/httpvideodriver.py
  labgrid/driver/usbaudiodriver.py
  labgrid/remote/client.py
Labels: fix

#1129 Drop support for Python 3.7, bump docker base image to bullseye
  .github/workflows/push-pr-unit-tests.yml
  .github/workflows/scheduled-unit-tests.yml
  dockerfiles/Dockerfile
  dockerfiles/staging/dut/Dockerfile
  pyproject.toml
Labels: docker, deprecation

#1147 github/build-and-release: also build wheel
  .github/workflows/build-and-release.yml
Labels: enhancement

#1079 Install Crossbar Into Separate Virtualenv
  .crossbar/config-anonymous.yaml
  .crossbar/config.yaml
  .github/workflows/reusable-unit-tests.yml
  CHANGES.rst
  crossbar-requirements.txt
  doc/RELEASE.rst
  doc/getting_started.rst
  dockerfiles/Dockerfile
  dockerfiles/staging/docker-compose.yml
  examples/usbpower/README.rst
  pyproject.toml
  tests/conftest.py
  tests/test_crossbar.py
Labels: dependencies

#1151 CHANGES: add bug fixes from 23.0.1
  CHANGES.rst
Labels: documentation

#1152 driver/serialdriver: drop handling of legacy pyserial 3.2.1
  labgrid/driver/serialdriver.py
  pyproject.toml
Labels: dependencies

#1136 Unpin labgrid's dependencies
  doc/RELEASE.rst
  man/labgrid-client.1
  man/labgrid-device-config.5
  man/labgrid-exporter.1
  pyproject.toml
Labels: dependencies

#1155 Rework Step information to use logging infrastructure #1106
  CHANGES.rst
  doc/configuration.rst
  labgrid/consoleloggingreporter.py
  labgrid/driver/bareboxdriver.py
  labgrid/driver/qemudriver.py
  labgrid/driver/serialdriver.py
  labgrid/driver/shelldriver.py
  labgrid/driver/smallubootdriver.py
  labgrid/driver/ubootdriver.py
  labgrid/logging.py
  labgrid/pytestplugin/__init__.py
  labgrid/pytestplugin/fixtures.py
  labgrid/pytestplugin/hooks.py
  labgrid/pytestplugin/reporter.py
  labgrid/remote/client.py
  labgrid/step.py
  labgrid/stepreporter.py
  labgrid/util/__init__.py
  labgrid/util/helper.py
  tests/test_steplogger.py
  tests/test_stepreporter.py
Labels: enhancement

#1158 readthedocs: specify Python version and OS
  .readthedocs.yaml
Labels: documentation
