Repository labgrid-project/labgrid, pull requests merged in 2023-01, with the labels that each got.

#1053 config: raise proper exception on empty config
  labgrid/config.py
Labels: enhancement

#1052 debian/doc/man: extend copyright period to 2023
  debian/copyright
  doc/conf.py
  man/labgrid-device-config.5
  man/labgrid-device-config.rst
  man/labgrid-exporter.1
  man/labgrid-exporter.rst
  man/labgrid-pytest.7
  man/labgrid-pytest.rst
  man/labgrid-suggest.1
  man/labgrid-suggest.rst
Labels: documentation

#1061 remote/exporter: stop event loop when register calls fail
  labgrid/remote/exporter.py
Labels: enhancement

#1065 pyproject.toml: drop six, move werkzeug to crossbar extras
  pyproject.toml
Labels: dependencies

#1067 Fix minor typo
  doc/getting_started.rst
Labels: documentation

#1066 Fix a typo
  doc/overview.rst
Labels: documentation

#1045 CI: add scheduled tests
  .github/workflows/push-pr-unit-tests.yml
  .github/workflows/reusable-unit-tests-docker.yml
  .github/workflows/reusable-unit-tests.yml
  .github/workflows/scheduled-unit-tests.yml
Labels: tests

#1083 dockerfiles: make execution of build.sh independent of cwd
  dockerfiles/build.sh
Labels: docker

#1085 pyproject.toml: remove xena extra from dev extra
  pyproject.toml
Labels: dependencies
