Repository labgrid-project/labgrid, pull requests merged in 2023-06, with the labels that each got.

#1186 pyproject.toml: move pysnmp -> pysnmp-lextudio, drop unnecessary pysnmp-mibs
  pyproject.toml
Labels: dependencies

#1198 udev/resource: fix mux device race condition leading to outdated control/disk paths
  labgrid/resource/udev.py
Labels: fix, Pick to stable

#1210 Fix handling disabled pytest logging plugin
  labgrid/pytestplugin/hooks.py
  tests/test_fixtures.py
Labels: fix

#1204 Add SEGGER J-Link vendor and model IDs to USBDebugger resource
  labgrid/resource/udev.py
Labels: enhancement

#1202 remote: Expose tags in RemotePlace
  labgrid/resource/remote.py
  tests/test_crossbar.py
Labels: enhancement

#1143 Support remote controlling Ykush devices
  doc/configuration.rst
  labgrid/driver/powerdriver.py
  labgrid/remote/client.py
  labgrid/remote/exporter.py
  labgrid/resource/__init__.py
  labgrid/resource/ykushpowerport.py
Labels: enhancement, work in progress

#1200 Fix stat command for MacOS
  labgrid/util/managedfile.py
Labels: enhancement

#1215 man/labgrid-device-config: add ykushcmd
  man/labgrid-device-config.5
  man/labgrid-device-config.rst
Labels: documentation
