Repository labgrid-project/labgrid, pull requests merged in 2023-03, with the labels that each got.

#1090 labgrid/driver/usbloader: fix uuu command
  doc/configuration.rst
  labgrid/driver/usbloader.py
Labels: fix, needs author info

#1101 usage: document labgrid-client allow
  doc/usage.rst
Labels: documentation

#1105 ssh: Use processwrapper for rsync
  labgrid/util/helper.py
  labgrid/util/ssh.py
Labels: enhancement

#1113 doc/configuration: fix SSHDriver's attribute indentation
  doc/configuration.rst
Labels: documentation

#1112 target: make get_resource() prioritize resources named "default" on ambiguous results
  labgrid/target.py
  man/labgrid-client.1
  man/labgrid-client.rst
  tests/test_target.py
Labels: enhancement

#1111 remote/client: allow specifying resources by name for various sub commands
  contrib/completion/labgrid-client.bash
  labgrid/remote/client.py
Labels: enhancement

#1054 tree-wide: send error messages to stderr instead of stdout
  labgrid/driver/httpvideodriver.py
  labgrid/remote/client.py
  labgrid/remote/coordinator.py
  labgrid/remote/exporter.py
  labgrid/resource/ethernetport.py
  labgrid/target.py
  labgrid/util/agents/network_interface.py
Labels: enhancement

#1120 driver/powerdriver: import urllib only when needed
  labgrid/driver/powerdriver.py
Labels: enhancement
