Repository labgrid-project/labgrid, pull requests merged in 2023-11, with the labels that each got.

#1283 client: fix console --loop on microcom error
  labgrid/remote/client.py
Labels: fix, Pick to stable

#1270 target: improve exceptions
  labgrid/target.py
Labels: enhancement

#1290 exporter: Use fqdn instead of hostname only
  labgrid/remote/exporter.py
  man/labgrid-exporter.1
  man/labgrid-exporter.rst
Labels: enhancement

#1298 tests: fix SSHDriver deactivation test
  tests/test_sshdriver.py
Labels: tests

#1300 github/workflows/docker: upgrade setuptools before installing setuptools_scm
  .github/workflows/docker.yml
  .github/workflows/reusable-unit-tests-docker.yml
Labels: docker
