Repository labgrid-project/labgrid, pull requests merged in 2024-01, with the labels that each got.

#1314 debian/doc/man: extend copyright period to 2024, rename next release 24.0
  CHANGES.rst
  debian/changelog
  debian/copyright
  doc/conf.py
  man/labgrid-device-config.5
  man/labgrid-device-config.rst
  man/labgrid-exporter.1
  man/labgrid-exporter.rst
  man/labgrid-pytest.7
  man/labgrid-pytest.rst
  man/labgrid-suggest.1
  man/labgrid-suggest.rst
Labels: documentation

#1157 Add RawNetworkInterfaceDriver, labgrid-raw-interface helper and example
  debian/labgrid.install
  doc/configuration.rst
  examples/network-test/env.yaml
  examples/network-test/pkg-replay-record.py
  helpers/labgrid-raw-interface
  labgrid/driver/__init__.py
  labgrid/driver/rawnetworkinterfacedriver.py
Labels: enhancement

#1323 remote/exporter: hostname option is ignored
  labgrid/remote/exporter.py
Labels: fix
