Repository labgrid-project/labgrid, pull requests merged in 2024-02, with the labels that each got.

#1326 labgrid-client.rst: replace 'status' with 'cycle'
  man/labgrid-client.1
  man/labgrid-client.rst
Labels: documentation

#1303 contrib: add helper to graph current configuration
  contrib/README.rst
  contrib/labgrid-webapp
  contrib/requirements-webapp.txt
Labels: enhancement

#1328 driver/resource: mqtt: use callback API v2, bump paho-mqtt>=2.0.0
  labgrid/driver/mqtt.py
  labgrid/resource/mqtt.py
  pyproject.toml
Labels: fix

#1329 github/workflows: update GitHub actions to latest versions
  .github/workflows/build-and-release.yml
  .github/workflows/reusable-unit-tests.yml
Labels: CI

#1331 resource: udev: add new USB ID for IMXUSBLoader
  labgrid/resource/udev.py
Labels: enhancement
