Repository labgrid-project/labgrid, pull requests merged in 2024-10, with the labels that each got.

#1518 udev: Adds model id for stlink-v2 and v3
  labgrid/resource/udev.py
Labels: enhancement

#1522 pyproject.toml: limit pysnmp's pyasn1 dependency to <0.6.0
  pyproject.toml
Labels: dependencies

#1519 doc: add support for sphinx_rtd_theme 3.0.0
  doc/conf.py
  man/Makefile
  man/labgrid-client.1
  man/labgrid-coordinator.1
  man/labgrid-device-config.5
  man/labgrid-exporter.1
  man/labgrid-pytest.7
  man/labgrid-suggest.1
Labels: documentation

#1510 github: bump ubuntu runner images to 24.04
  .github/workflows/docker.yml
  .github/workflows/reusable-unit-tests-docker.yml
  .github/workflows/reusable-unit-tests.yml
Labels: CI

#1508 update codecov/codecov-action v3 -> v4
  .github/workflows/reusable-unit-tests.yml
Labels: CI

#1526 util/agents/usb_hid_relay: fix concurrent access
  labgrid/util/agents/usb_hid_relay.py
Labels: fix

#1320 Rawnetworkinterface stream
  helpers/labgrid-raw-interface
  labgrid/driver/rawnetworkinterfacedriver.py
Labels: enhancement

#1524 pyproject.toml: use recursive dependencies
  pyproject.toml
Labels: dependencies

#1529 github/workflows: set the python version as a codecov flag
  .github/workflows/reusable-unit-tests.yml
Labels: tests

#1531 github/workflows: upload test results to codecov
  .github/workflows/reusable-unit-tests.yml
Labels: tests
