Repository labgrid-project/labgrid, pull requests merged in 2024-08, with the labels that each got.

#1460 docker: move to Docker compose v2
  .github/workflows/docker.yml
  .github/workflows/reusable-unit-tests-docker.yml
  dockerfiles/README.rst
  dockerfiles/staging/docker-compose.yml
Labels: docker

#1463 remote/client: suggest non-deprecated env var LG_PLACE instead of PLACE
  labgrid/remote/client.py
Labels: enhancement

#1464 add support for the LCTech LCUS USB
  doc/configuration.rst
  labgrid/resource/udev.py
  labgrid/util/agents/usb_hid_relay.py
Labels: enhancement

#1465 CHANGES: more updates for 24.0 release
  CHANGES.rst
Labels: documentation

#1475 github/workflows/scheduled-unit-tests: drop scheduled docker tests on stable-23.0
  .github/workflows/scheduled-unit-tests.yml
Labels: CI
