Repository labgrid-project/labgrid, pull requests merged in 2024-04, with the labels that each got.

#1351 driver/usbstoragedriver: use udisk2 only when calling write_file
  labgrid/driver/usbstoragedriver.py
Labels: fix

#1366 dockerfiles: replace wait-for-it dependency with simple bash loop
  dockerfiles/Dockerfile
  dockerfiles/staging/docker-compose.yml
Labels: docker

#1371 doc/configuration: UUUDriver: align example with reality
  doc/configuration.rst
Labels: documentation

#1364 man/labgrid-client: fix/extend positional arguments
  man/labgrid-client.1
  man/labgrid-client.rst
Labels: documentation

#1373 shelldriver: allow dashes and dots in device names
  labgrid/driver/shelldriver.py
  tests/test_shelldriver.py
Labels: enhancement
