Repository labgrid-project/labgrid, pull requests merged in 2024-07, with the labels that each got.

#1430 util/ssh: stop keepalive in disconnect() when existing connection is used
  labgrid/util/ssh.py
Labels: fix

#1440 driver/externalconsoledriver: use bufsize=0 for opening external process
  labgrid/driver/externalconsoledriver.py
Labels: fix

#1307 Publish arm64 Docker images
  .github/workflows/docker.yml
  dockerfiles/README.rst
  dockerfiles/build.sh
  dockerfiles/staging/docker-compose.yml
Labels: enhancement, needs author info, docker

#1448 doc/usage: adjust docs for legacy --lg-colored-steps, LG_COLOR_SCHEME
  doc/usage.rst
Labels: documentation

#1446 StepLogger documentation and warning fix
  doc/configuration.rst
  doc/development.rst
  labgrid/logging.py
Labels: documentation
