Repository labgrid-project/labgrid, pull requests merged in 2024-03, with the labels that each got.

#1322 doc/configuration: update/fix bindings, protocols and resource usage
  doc/configuration.rst
Labels: documentation

#1334 resource: udev: also suggest ID_USB_INTERFACE_NUM for USBResource
  doc/configuration.rst
  labgrid/resource/udev.py
Labels: enhancement

#1302 driver/pyvisadriver: add optional backend property
  doc/configuration.rst
  labgrid/driver/pyvisadriver.py
  labgrid/resource/pyvisa.py
Labels: work in progress

#1339 Resource: add udev based Sysfs GPIO support
  doc/configuration.rst
  labgrid/remote/exporter.py
  labgrid/resource/__init__.py
  labgrid/resource/suggest.py
  labgrid/resource/udev.py
Labels: enhancement

#1342 driver/sshdriver: fix caching of _ssh_version
  labgrid/driver/sshdriver.py
Labels: fix

#1219 remote/client: implement udisks2-using write-files command
  CHANGES.rst
  contrib/completion/labgrid-client.bash
  doc/configuration.rst
  labgrid/driver/usbstoragedriver.py
  labgrid/remote/client.py
  labgrid/util/agents/udisks2.py
  man/labgrid-client.1
  man/labgrid-client.rst
Labels: enhancement

#1343 doc/overview: mention SSH requirement
  doc/overview.rst
Labels: documentation

#1344 doc/configuration: fix spelling of MatchedSysfsGPIO class name
  doc/configuration.rst
Labels: documentation, fix
