Repository labgrid-project/labgrid, pull requests merged in 2024-06, with the labels that each got.

#1426 configure ruff format and run it on all remote modules
  labgrid/remote/client.py
  labgrid/remote/common.py
  labgrid/remote/config.py
  labgrid/remote/coordinator.py
  labgrid/remote/exporter.py
  pyproject.toml
Labels: grpc

#1385 CHANGES: update changelog for 24.0 release
  CHANGES.rst
Labels: documentation

#1412 remote/client: fallback to telnet when microcom is not available
  CHANGES.rst
  doc/getting_started.rst
  labgrid/remote/client.py
Labels: enhancement

#1404 console: Make settle() indicate success/failure
  labgrid/driver/consoleexpectmixin.py
Labels: enhancement

#1346 driver/sigrok: various fixes
  labgrid/driver/sigrokdriver.py
Labels: fix

#1388 doc/development: document await_resources
  doc/development.rst
Labels: documentation

#1432 driver/serialdigitaloutput: fix get() for DTR signal
  labgrid/driver/serialdigitaloutput.py
Labels: fix
