Repository labgrid-project/labgrid, pull requests merged in 2025-01, with the labels that each got.

#1565 readthedocs: set explicit sphinx configuration and bump Ubuntu/Python
  .readthedocs.yaml
Labels: documentation

#1573 remote/exporter: fix info message for version
  labgrid/remote/exporter.py
  tests/conftest.py
Labels: fix

#1572 remote: add support for pystuck
  labgrid/remote/coordinator.py
  labgrid/remote/exporter.py
  pyproject.toml
Labels: enhancement

#1574 improve gRPC robustness
  labgrid/remote/coordinator.py
  labgrid/remote/exporter.py
Labels: fix, grpc

#1579 improve handing of background tasks in the coordinator
  labgrid/remote/coordinator.py
Labels: enhancement

#1578 remote/exporter: poll resource on add
  labgrid/remote/exporter.py
Labels: enhancement

#1590 Extend copyright period to 2025
  CHANGES.rst
  debian/changelog
  debian/copyright
  doc/conf.py
  man/labgrid-client.1
  man/labgrid-client.rst
  man/labgrid-coordinator.1
  man/labgrid-coordinator.rst
  man/labgrid-device-config.5
  man/labgrid-device-config.rst
  man/labgrid-exporter.1
  man/labgrid-exporter.rst
  man/labgrid-pytest.7
  man/labgrid-pytest.rst
  man/labgrid-suggest.1
  man/labgrid-suggest.rst
Labels: documentation
