Repository labgrid-project/labgrid, pull requests merged in 2025-02, with the labels that each got.

#1580 refactor handling of orphaned resources in the coordinator
  labgrid/remote/coordinator.py
Labels: enhancement

#1595 driver/networkinterfacedriver: add wait_state()'s expected argument to step
  labgrid/driver/networkinterfacedriver.py
Labels: enhancement

#1597 dockerfiles/build.sh: fix buildx detection
  dockerfiles/build.sh
Labels: docker

#1562 labgrid/resource/remote: add missing sigrok channel_group parameter
  labgrid/resource/remote.py
Labels: fix

#1558 driver/sshdriver: read from tools
  labgrid/driver/sshdriver.py
  man/labgrid-device-config.5
  man/labgrid-device-config.rst
  tests/test_sshdriver.py
Labels: enhancement

#1605 remote/client: suppress gRPC error message on shutdown
  labgrid/remote/client.py
Labels: grpc

#1607 remote: client: fix empty sys.excepthook error work around
  labgrid/remote/client.py
Labels: grpc

#1615 CHANGES: update changelog for 25.0 release
  CHANGES.rst
Labels: documentation

#1620 contrib/systemd/labgrid-exporter: move StartLimitIntervalSec from Service to Unit section
  contrib/systemd/labgrid-exporter.service
Labels: fix

#1455 remote/config: simplify ResourceConfig template loading
  labgrid/remote/config.py
Labels: enhancement

#1431 driver/power/tplink: use IotStrip instead of deprecated SmartStrip
  labgrid/driver/power/tplink.py
  pyproject.toml
Labels: dependencies
