Repository labgrid-project/labgrid, pull requests merged in 2025-07, with the labels that each got.

#1664 NetworkPowerPort: add support for Shelly Gen2+
  doc/configuration.rst
  labgrid/driver/power/shelly_gen2.py
  pyproject.toml
Labels: enhancement

#1682 doc/configuration: fix ubus/sysfs links, sort power backends
  doc/configuration.rst
Labels: documentation

#1617 doc: use importlib.metadata in favor of pkg_resources in conf.py
  doc/conf.py
Labels: documentation, fix, Pick to stable

#1697 doc: describe all network resources
  doc/configuration.rst
Labels: documentation

#1705 doc/configuration: add more info on TFTP server requirements
  doc/Makefile
  doc/configuration.rst
Labels: enhancement, documentation

#1696 WaveShare Modbus Fixes
  doc/configuration.rst
  labgrid/driver/__init__.py
Labels: documentation
